'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApplication1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  1.54 M に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property COGValue() As String
            Get
                Return ResourceManager.GetString("COGValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cost of Goods に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property CostOfGoods() As String
            Get
                Return ResourceManager.GetString("CostOfGoods", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  .44 M に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property OEValue() As String
            Get
                Return ResourceManager.GetString("OEValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Operating Expense に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property OperatingExpense() As String
            Get
                Return ResourceManager.GetString("OperatingExpense", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Print Preview に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property PrintButton() As String
            Get
                Return ResourceManager.GetString("PrintButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Profit に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property Profit() As String
            Get
                Return ResourceManager.GetString("Profit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  .22 M に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property PValue() As String
            Get
                Return ResourceManager.GetString("PValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Quarterly Results に類似しているローカライズされた文字列を検索します。
        '''</summary>
        Friend ReadOnly Property ReportTitle() As String
            Get
                Return ResourceManager.GetString("ReportTitle", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
